### ISSUE TITLE
Comments after a quick review of source

### ISSUE THREAD

**Issue by bkamins** [JuliaData/SentinelArrays.jl#1]
1. Maybe add `SentinelMatrix` also to match standard definitions in Base?
2. `rand(T)` fails for many bits types, e.g. `Tuple{Int,Int}`. Maybe `rand` should take function of `T` that converts it to integer first?
3. in general I think global `rand` should not be used as it messes up global prng (and user code might rely on the fact that you do not touch it). I would prefer to have a package local set of PRNGs (as many as there are threads so that the package is tread safe). Also as you set compat to `julia=1` it is even more important as Julia 1.0 does not have threadsafe PRNG.

**Comment by quinnj** [comment]
There's a pretty good work-around for those cases, which is doing `SentinelVector{Union{UInt8, Missing}}(undef, len, missing, missing)`. I.e. we just use a `Vector{Union{T, Missing}}` as the underlying storage w/ `missing` as the sentinel. Of course, you pretty much lose all advantage of using the package, but if you really require using SentinelArrays.jl for some reason, that will "just work". I think in CSV.jl, we'll either use that approach for small enough types or just use `Vector{Union{T, Missing}}` directly.

**Comment by bkamins** [comment]
I think what @ExpandingMan points is a valid problem - not only about the probability of collision but just because the pool of sentinels is likely to be exhausted:
```
x = SentinelVector{UInt8}(undef, 256)
for i in 0:255
    x[i] = i
end
```
currently hangs in an infinite `while` loop.

The issue is relevant for 32-bit or less types as it is easily possible to "fill-in" the address space for them (for larger types it is unlikely to be relevant but still on very large machines even e.g. 40-bit type can have this problem).

What are the solutions. So either you accept this problem (and warn a user not to use SentinelArrays.jl in such cases) or the internal storage should be automatically promoted to `Union`-with `Missing` for small types (maybe there also some other options but these two are the first that came to my mind).

**Comment by bkamins** [comment]
@quinnj - after some more thought. A bigger problem with this code is that it is not threadsafe I think.

The two problematic cases are:
1. threads A and B try to update sentinel at the same time
2. thread A just does `setindex!` (no sentinel update) but at the same time thread B changes sentinel

So either appropriate locks should be put in the code (but it might kill performance especially for `setindex!`) or simply it should be clearly stated that the package is not threadsafe and all work on the `SentinelArray` should be always made on a single thread.

**Comment by quinnj** [comment]
Ok, here are my latest thoughts mulling it over the last day or two:

* I think we'll clearly document that by default, SentinelArrays will do *some* automatic sentinel management, cycling it if you try to set it; but I think a reasonable solution to the infinite while loop is to attempt 3-4 new sentinels and if each fail (i.e. they already exist in the data), throw an error. I still think there's a valid use-case for people doing `SentinelVector{UInt8}(undef, 10, typemax(UInt8), missing)` and they're careful in their own code to track the sentinel use. I think we should still allow this "controlled" usage by users and not do anything too magical underneath like auto-promoting. 
* I'd like to just throw an error for `SentinelVector{Bool}` and suggest using `SentinelVector{Union{Bool, Missing}}`
* I'm not currently very worried about the thread-safety of indexing on SentinelArrays, mainly because `Base.Array` itself isn't (and doesn't claim to be) thread-safe. i.e. if threads A and B tyr to `setindex!` on an `Array` at the same time, you very quickly get into memory-cache-line clashes and things get messed up. The one use-case we *aren't* setup to handle is if the `AbstractArray` you wrap in `SentinelArray` *IS* thread-safe, then the `SentinelArray` indexing *won't* be thread-safe, which could be a problem. But then again, I actually don't know of any thread-safe `AbstractArray` types out there. The pattern so far in Julia (I suspect w/ threading still maturing across the ecosystem) is to make/manage your own locks on datastructures, which is what we'll recommend to users in SentinelArrays.

**Comment by bkamins** [comment]
> I'm not currently very worried about the thread-safety of indexing on SentinelArrays

This should a valid Julia code for any `AbstractArray` now (maybe it is even idiomatic?):
```
Threads.@threads for i in 0:255
    x[i] = i
end
```
but if `x` is a `SentinelArray` it can hit race condition problem as I have commented earlier.

**Comment by quinnj** [comment]
I disagree? I'd be very surprised if you didn't eventually run into race conditions with code like that, especially if `x` is a plain `Array`. I'm pretty familiar with the `array.c` code and there's no builtin thread safety. Even if the threads are operating on separate elements, things still get messed up at a lower-level; i.e. to "store" an element, the CPU will load an entire cache-line of memory for the array to set; and if a separate core does the same thing at the same time, things get out of sync. I'll see if I can dig up some existing threads on why this isnt' guaranteed to work.

**Comment by quinnj** [comment]
Like here: https://docs.julialang.org/en/v1.6-dev/manual/multi-threading/#Caveats-1, first bullet point

**Comment by quinnj** [comment]
Here's a pretty good thread: https://discourse.julialang.org/t/editing-an-array-with-multiple-threads/25364/14. I guess the conclusion there is that it might be _technically_ correct, but will result in massive slowdowns, and the general recommendation there is to partition the array into chunks for each thread or use a lock.

**Comment by quinnj** [comment]
Ok, so it seems I'm probably wrong here and that we should handle the case @bkamins mentions (i.e. multiple threads doing `setindex!` on a SentinelArray at the same time (though different indices)`. I'll look into what implementing that would look like.

**Comment by quinnj** [comment]
Ok, looking into this a bit further, I don't think we can support thread-safety internally. It would require doing a `lock` on every `setindex!` which would be too expensive to impose on non-threaded code. As I mentioned before though, you could still use a SentinelArray in the "controlled" case where you're aware of the sentinel being set and that there won't be inadvertent collisions; there's also the solutions of using a SentinelArray per thread or wrapping a SentinelArray with your own lock. I'll make sure it's clearly documented, along with the rest of the list of growing caveats 😅

**Comment by bkamins** [comment]
>  i.e. to "store" an element, the CPU will load an entire cache-line of memory for the array to set;

You do not have to think about it. If cache gets invalidated then CPU should be smart enough to reload it, but then you can get a very slow code in some cases due to [false sharing](https://en.wikipedia.org/wiki/False_sharing).

> I don't think we can support thread-safety internally.

This is what I meant above when I said "and warn a user not to use SentinelArrays.jl in such cases" - as locking will kill performance here as you note. For practical usage - as you say - users should be warned to create one `SentinelArray` per thread and then eventually merge them (I guess this is your current intention - right?).

**Comment by quinnj** [comment]
Yeah, the reality is that you only need to worry about sentinel collision, and therefore thread safety, if you're dealing with `Int8`/`Int16`/`Int32` eltypes. For floats and TimeTypes, we're using "invalid" bit patterns for sentinel, so there's no risk of collision. Similarly for non-isbitstype, since we're using `#undef`. I've updated the docs to reflect as such. I think in CSV.jl, if we allow users to pass custom types like `Int8`/`Int32` then we'll use `Vector{Union{T, Missing}}` instead of SentinelArrays for safety.
